### ISSUE TITLE
Changing from raw_input to input in the code

### ISSUE THREAD

**Issue by UncleAwesome2** [MOS6510/AbootHDDConverter#1]
Hi. 

I don't program phyton or anything so I don't know if I made any sort of mistake. But I got an error message when running your pyhton script. So I changed all the raw_input to just input and then the code worked.

**Comment by MOS6510** [comment]
Hi UncleAwesome2,

yes, you get this error when using the script running with Python 3 because it's not supported anymore. 
I wrote this script with Python 2. I have to fix it. Until then you can replace "raw_input" with "input".
BR

**Comment by MOS6510** [comment]
I reworked the complete script. Now it should be working with Python 3...
